Logs:
  GinLogName: "/Users/zhao/Desktop/Code/Go/GoCode/web/gin/logs/gin.log"                  #设置 gin 框架的接口访问日志
  TextFormat: "console"                                #记录日志的格式，参数选项：console、json ， console 表示一般的文本格式
  TimePrecision: "second"                         #记录日志时，相关的时间精度，该参数选项：second  、 millisecond ， 分别表示 秒 和 毫秒 ,默认为毫秒级别
  MaxSize: 256                                           #每个日志的最大尺寸(以MB为单位）， 超过该值，系统将会自动进行切割
  MaxBackups: 10                                        #保留旧日志最大个数
  MaxAge: 15                                           #保留旧日志最大天数
  Compress: false                                      #日志备份时，是否进行压缩

Gormv2: # 只针对 gorm  操作数据库有效
  UseDbType: "mysql"
  LiveRecord:
    IsInitGolobalGormMysql: 1    # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Write:
      Host: 127.0.0.1
      DataBase: "live_record"
      Port: 3306                        #注意，非3306，请自行调整
      User: "root"
      Pass: "root"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 600    # 连接不活动时的最大生存时间(秒)

redis:
  addr: 127.0.0.1:6379
  database: 0
  password: ""
